# Generated by Django 4.1 on 2022-09-09 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0009_alter_city_options_alter_state_options_amenity"),
    ]

    operations = [
        migrations.RemoveField(model_name="amenity", name="property",),
        migrations.AddField(
            model_name="property",
            name="amenity",
            field=models.ManyToManyField(
                related_name="properties", to="organizations.amenity"
            ),
        ),
    ]
