# Generated by Django 3.2.15 on 2022-09-12 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slotapp', '0004_remove_slot_user'),
        ('organizations', '0014_remove_booking_is_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='slot',
        ),
        migrations.AddField(
            model_name='booking',
            name='slot',
            field=models.ManyToManyField(blank=True, null=True, related_name='booking_slot', to='slotapp.Slot'),
        ),
    ]
