# Generated by Django 3.2.15 on 2022-09-12 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0015_auto_20220912_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='isBooking',
            field=models.BooleanField(default=False),
        ),
    ]
