# Generated by Django 3.2.15 on 2022-09-14 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0018_alter_amenity_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='isBooking',
            new_name='isBooked',
        ),
    ]
