# Generated by Django 3.2.15 on 2022-10-07 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0023_auto_20221006_1021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='property',
        ),
        migrations.AddField(
            model_name='property',
            name='image',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='property_images', to='organizations.images'),
        ),
    ]
