# Generated by Django 3.2.15 on 2022-10-07 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0024_auto_20221007_0613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
