# Generated by Django 3.2.15 on 2022-10-07 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0025_alter_images_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='image',
        ),
        migrations.DeleteModel(
            name='Images',
        ),
    ]
