# Generated by Django 3.2.15 on 2022-10-07 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0027_auto_20221007_0708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
