# Generated by Django 4.1 on 2022-09-02 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('city', models.CharField(blank=True, max_length=256, null=True)),
                ('state', models.CharField(blank=True, max_length=256, null=True)),
                ('image', models.ImageField(upload_to='organizations/static/imgs')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('is_available', models.BooleanField(default=True)),
                ('rent', models.FloatField(blank=True, null=True)),
                ('turf_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='organizations.turfcategory')),
            ],
        ),
    ]
