# Generated by Django 3.2.15 on 2022-11-01 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_remove_property_image_images_property'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
