# Generated by Django 3.2.15 on 2022-09-08 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_city_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='latitude',
            field=models.FloatField(default=20.5937),
        ),
        migrations.AddField(
            model_name='city',
            name='longitude',
            field=models.FloatField(default=78.9629),
        ),
    ]
