# Generated by Django 4.1 on 2022-09-09 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0010_remove_amenity_property_property_amenity"),
    ]

    operations = [
        migrations.RemoveField(model_name="transaction", name="booking",),
    ]
