# Generated by Django 3.2.15 on 2022-09-12 09:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('slotapp', '0004_remove_slot_user'),
        ('organizations', '0012_booking_transaction_alter_transaction_rent_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='end_at',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='property',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='start_at',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='transaction',
        ),
        migrations.AddField(
            model_name='booking',
            name='slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_slot', to='slotapp.slot'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_booking', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='property',
            name='amenity',
            field=models.ManyToManyField(related_name='property_amenities', to='organizations.Amenity'),
        ),
        migrations.AlterField(
            model_name='property',
            name='owner',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='property_owners', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
