# Generated by Django 3.2.15 on 2022-09-14 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0017_remove_booking_slot'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amenity',
            options={'ordering': ['name']},
        ),
    ]
