# Generated by Django 4.1 on 2022-09-11 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0012_booking_transaction_alter_transaction_rent_amount'),
        ('slotapp', '0002_alter_slot_property_alter_slot_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='organizations.property'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slots', to=settings.AUTH_USER_MODEL),
        ),
    ]
